curr_supported = [
    app_commands.Choice(name="USD", value="usd"),
    app_commands.Choice(name="EUR", value="eur"),
    app_commands.Choice(name="HKD", value="hkd"),
    app_commands.Choice(name="CAD", value="cad"),
    app_commands.Choice(name="NZD", value="nzd"),
    app_commands.Choice(name="SGD", value="sgd"),
    app_commands.Choice(name="AUD", value="aud"),
    app_commands.Choice(name="CHF", value="chf"),
    app_commands.Choice(name="GBP", value="gbp"),
    app_commands.Choice(name="UAH", value="uah"),
    app_commands.Choice(name="CZK", value="czk"),
    app_commands.Choice(name="DKK", value="dkk"),
    app_commands.Choice(name="NOK", value="nok"),
    app_commands.Choice(name="SEK", value="sek"),
    app_commands.Choice(name="RON", value="ron"),
    app_commands.Choice(name="BGN", value="bgn"),
    app_commands.Choice(name="TRY", value="try"),
    app_commands.Choice(name="ILS", value="ils"),
    app_commands.Choice(name="PHP", value="php"),
    app_commands.Choice(name="MXN", value="mxn"),
    app_commands.Choice(name="ZAR", value="zar"),
    app_commands.Choice(name="BRL", value="brl"),
    app_commands.Choice(name="MYR", value="myr"),
    app_commands.Choice(name="CNY", value="cny"),
    app_commands.Choice(name="XDR", value="xdr")
]